### PR TITLE
Redesigned RobotMap (2016-Code analogue)

### PR DESCRIPTION
**Pull request by carturn**
Redesigned RobotMap.Java, mirroring Yoni's 2016-Code changes.

### CODE REVIEW

**Comment by tylkahn** [comment]
To merge or not to merge. That is the question.

**Comment by ajnadel** [comment]
To comment on our team's pull requests -- that is a privilege

**Comment by carturn** [comment]
Tested.
(And yes, it works)

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
